---
- hosts: all
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Deploy Application
      command: kubectl apply -f /path/to/k8s/deployment.yaml
 
